### ISSUE TITLE
Mad in the Netherlands

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/awesome-mentalhealth#21]
@martijndeb I just found this, but I'm not sure you'll believe it's a good resource: https://madinthenetherlands.org/

**Comment by martijndeb** [comment]
Looks to be highly opiniated, and has a large set of data about stopping with medication. How trustworthy is the American version?

**Comment by andy5995** [comment]
>How trustworthy is the American version?

The founder of the site is Robert Whitaker, the author of Anatomy of an Epidemic. There's a review of his book by [John Horgan](https://www.scientificamerican.com/author/john-horgan7/), an author on the Scientific American blog: https://www.scientificamerican.com/blog/cross-check/are-psychiatric-medications-making-us-sicker/

**Comment by martijndeb** [comment]
I trust your judgement on this, thanks for clarifying. We can add them

**Comment by andy5995** [comment]
Ok, thank you for trusting my judgment. :)  If you ever change your mind and discover my judgment has been corrupted by billions of dollars given to me by any organization, please let me know and I'll remove the links. :)
